In [1]:
#Topic: Basic Array Arithmetic Laboratory
#1. Create two NumPy arrays representing the prices of 5 items in a store and the quantity sold. Calculate the total revenue per item.

import numpy as np

# Prices of 5 items (in whatever currency you use)
prices = np.array([120, 250, 80, 300, 150])

# Quantity sold for each of the 5 items
quantities = np.array([5, 3, 10, 2, 7])

# Total revenue per item = price * quantity (element-wise multiplication)
revenue_per_item = prices * quantities

print("Prices:       ", prices)
print("Quantities:   ", quantities)
print("Revenue/item: ", revenue_per_item)
print("Total revenue:", revenue_per_item.sum())

Prices:        [120 250  80 300 150]
Quantities:    [ 5  3 10  2  7]
Revenue/item:  [ 600  750  800  600 1050]
Total revenue: 3800


In [2]:
#Topic: Data Range Analysis with Min/Max
#2. You are given a list of daily temperatures. Use NumPy to find the hottest day, the coldest day, and the temperature range (max - min).
import numpy as np

# Example list of daily temperatures (replace with your data)
temperatures = [28.5, 31.2, 27.8, 33.0, 29.4, 26.1, 30.7]

# Convert to NumPy array
temp_array = np.array(temperatures)

# Hottest and coldest temperatures
max_temp = temp_array.max()
min_temp = temp_array.min()

# Index (day number) of hottest and coldest day
hottest_day_index = temp_array.argmax()   # 0-based index
coldest_day_index = temp_array.argmin()   # 0-based index

# Temperature range
temp_range = max_temp - min_temp

print("Temperatures:        ", temp_array)
print("Hottest temperature: ", max_temp, "on day", hottest_day_index + 1)
print("Coldest temperature: ", min_temp, "on day", coldest_day_index + 1)
print("Temperature range:   ", temp_range)


Temperatures:         [28.5 31.2 27.8 33.  29.4 26.1 30.7]
Hottest temperature:  33.0 on day 4
Coldest temperature:  26.1 on day 6
Temperature range:    6.899999999999999


In [3]:
#Topic: Memory Footprint Comparison
#3. Compare the memory consumption of a Python list containing 1 million integers vs a NumPy array containing the same integers.

import sys
import numpy as np

# Create data
py_list = list(range(1_000_000))        # Python list
np_array = np.arange(1_000_000)         # NumPy array (int64 by default)

N = len(py_list)

# Approximate memory for Python list:
# - list container
# - 8 bytes per reference (64-bit)
# - ~28 bytes per int object (worst case, no caching)
list_container = sys.getsizeof(py_list)
list_approx_total = list_container + 8 * N + 28 * N

# Memory for NumPy array:
# - array object
# - data buffer (8 bytes per int64)
np_container = sys.getsizeof(np_array)
np_data = np_array.nbytes
np_approx_total = np_container + np_data

print(f"Python list (approx total): {list_approx_total / 1_048_576:.2f} MB")
print(f"NumPy array (approx total): {np_approx_total / 1_048_576:.2f} MB")
print(f"List is about {list_approx_total / np_approx_total:.2f}x larger than NumPy array")

Python list (approx total): 41.96 MB
NumPy array (approx total): 15.26 MB
List is about 2.75x larger than NumPy array


In [4]:
#Topic: Navigating Multi-Dimensional Arrays
#4. Create a 3x3 matrix representing a Tic-Tac-Toe board and perform specific indexing tasks to retrieve rows, columns, and individual cells.

import numpy as np

# Create a 3x3 Tic-Tac-Toe board
# 0 = empty, 1 = X, 2 = O (you can use any coding you like)
board = np.array([
    [1, 0, 2],
    [0, 1, 0],
    [2, 0, 1]
])

print("Board:")
print(board)

# Retrieve rows
row_0 = board[0, :]   # First row
row_1 = board[1, :]   # Second row
row_2 = board[2, :]   # Third row

print("\nRows:")
print("Row 0:", row_0)
print("Row 1:", row_1)
print("Row 2:", row_2)

# Retrieve columns
col_0 = board[:, 0]   # First column
col_1 = board[:, 1]   # Second column
col_2 = board[:, 2]   # Third column

print("\nColumns:")
print("Col 0:", col_0)
print("Col 1:", col_1)
print("Col 2:", col_2)

# Retrieve individual cells
top_left     = board[0, 0]
top_center   = board[0, 1]
top_right    = board[0, 2]
middle_left  = board[1, 0]
center       = board[1, 1]
middle_right = board[1, 2]
bottom_left  = board[2, 0]
bottom_center= board[2, 1]
bottom_right = board[2, 2]

print("\nIndividual cells:")
print("Top-left:", top_left, "Top-center:", top_center, "Top-right:", top_right)
print("Middle-left:", middle_left, "Center:", center, "Middle-right:", middle_right)
print("Bottom-left:", bottom_left, "Bottom-center:", bottom_center, "Bottom-right:", bottom_right)

Board:
[[1 0 2]
 [0 1 0]
 [2 0 1]]

Rows:
Row 0: [1 0 2]
Row 1: [0 1 0]
Row 2: [2 0 1]

Columns:
Col 0: [1 0 2]
Col 1: [0 1 0]
Col 2: [2 0 1]

Individual cells:
Top-left: 1 Top-center: 0 Top-right: 2
Middle-left: 0 Center: 1 Middle-right: 0
Bottom-left: 2 Bottom-center: 0 Bottom-right: 1


In [5]:
#Topic: High-Performance Data Aggregation
#5. Represent a 2D dataset of 100 students and their scores across 4 subjects. Find which subject performed worst and apply a 'grace mark' boost to those who scored below a threshold.

import numpy as np

# Simulate a 2D dataset: 100 students × 4 subjects
# Each score between 0 and 100 (you can replace with real data)
np.random.seed(42)
scores = np.random.randint(0, 101, size=(100, 4))

subjects = ["Math", "Science", "English", "History"]

# 1. Find which subject performed worst (by average score)
avg_by_subject = scores.mean(axis=0)
worst_subject_index = avg_by_subject.argmin()
worst_subject = subjects[worst_subject_index]

print("Average score by subject:")
for i, subj in enumerate(subjects):
    print(f"{subj}: {avg_by_subject[i]:.2f}")

print(f"\nWorst-performing subject: {worst_subject} (avg = {avg_by_subject[worst_subject_index]:.2f})")

# 2. Apply grace marks to students scoring below a threshold in that subject
threshold = 40
grace = 10  # grace marks to add

# Identify students below threshold in the worst subject
below_threshold_mask = scores[:, worst_subject_index] < threshold

# Apply grace marks only to those students, in that subject only
scores[below_threshold_mask, worst_subject_index] += grace

# Optional: cap at 100 so no one exceeds 100
scores[:, worst_subject_index] = np.clip(scores[:, worst_subject_index], 0, 100)

print(f"\nApplied +{grace} grace marks in {worst_subject} to students scoring below {threshold}.")
print(f"Number of students who received grace: {below_threshold_mask.sum()}")

# Show new average for that subject
new_avg_worst = scores[:, worst_subject_index].mean()
print(f"New average for {worst_subject}: {new_avg_worst:.2f}")

Average score by subject:
Math: 49.20
Science: 52.79
English: 54.37
History: 43.62

Worst-performing subject: History (avg = 43.62)

Applied +10 grace marks in History to students scoring below 40.
Number of students who received grace: 49
New average for History: 48.52
